package net.iessochoa.sergiocontreras.jcadapters

fun getAllFoods() = listOf(
    Food(name = "Hamburguesa",
        description = "Hamburguesa de ternera con queso, lechuga, tomate y cebolla",
        imgUrl = "https://picsum.photos/320/240"),
    Food(name = "Pizza",
        description = "Pizza con tomate, mozzarella, jamón y champiñones",
        imgUrl = "https://picsum.photos/320/241"),
    Food(name = "Sushi",
        description = "Sushi variado de salmón, atún y aguacate",
        imgUrl = "https://picsum.photos/320/242"),
    Food(name = "Ensalada",
        description = "Ensalada con lechuga, tomate, pepino, cebolla y aceitunas",
        imgUrl = "https://picsum.photos/320/243"),
    Food(name = "Pasta",
        description = "Pasta con salsa de tomate y carne picada",
        imgUrl = "https://picsum.photos/320/244"),
    Food(name = "Tacos",
        description = "Tacos de carne asada con cilantro, cebolla y salsa",
        imgUrl = "https://picsum.photos/320/245"),
    Food(name = "Sopa",
        description = "Sopa de pollo con verduras y fideos",
        imgUrl = "https://picsum.photos/320/246"),
    Food(name = "Pescado",
        description = "Pescado a la plancha con patatas y verduras",
        imgUrl = "https://picsum.photos/320/247"),
    Food(name = "Pollo",
        description = "Pollo asado con patatas y ensalada",
        imgUrl = "https://picsum.photos/320/248"),
    Food(name = "Arroz",
        description = "Arroz con verduras y pollo",
        imgUrl = "https://picsum.photos/320/249"),
    )
